### PR TITLE
Modal opens when search field is outside topbar

### PR DESCRIPTION
**Pull request by diogogpinto**
This PR introduces the ability to open the search field when placed outside the `.fi-topbar` container class. This means that when search is added to sidebar, modal still opens.

Also, keeps the input visible to avoid breaking container height, when `.fi-global-search-field` is placed on a vertical container.

This was motivated because I have been creating new Filament themes and I always include this package for better search experience and I thought it could be useful for the community.

Thank you for your work.

### CODE REVIEW

**Comment by CharrafiMed** [comment]
hey @diogogpinto thank you.
I have no problem merging this PR  but I have a question why did you remove the ``node.style.display = "none";`` this is make the UX bad not as previous

**Comment by diogogpinto** [comment]
Thank you for your feedback @CharrafiMed 

I removed, to keep the input visible to avoid breaking container heights when search is in a vertical container. Also, when the blur is lighter, the input stays there and stays visible. I don't know if it only affects my use case, but it seemed a better UX for me to keep the input visible on the background. Check example below, every feedback is appreciated.

Captura de ecrã 2024-10-16, às 21 57 06

**Comment by CharrafiMed** [comment]
yeah I see in your case it indeed needs to persist in the UI, Oki no problem  for me

**Comment by diogogpinto** [comment]
@CharrafiMed this was my first ever PR to a Open Source project. Thank you! I hope I helped better this plugin.

**Pull request merged**
